language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
  user: "mkb79"
  password:
    secure: fmONemS+G/JrvI9hVSkrS6hXRbQOwWKLjEvXYt5M4wEgW/nfmcaDrAX2rhcPDCByE7aZe0frt9BVAp0HJeQTh/BC4O0AGs84Vg987geNT1h5bzVxX3/l0z2lke4Mre//VlO9Mwy0bAUsc4oj3EoFncycnbab6/SKrDKqP5reHQtGfKgQiLM2j2V/3FXIyKvMf19jl0QLJM1dZ0nMONQ5vkrCzqEAvGT16iNQvgSmv8RiUYufl5Yntt96MgGzwU9xs6ExTtyEnM4cF9akf9M85UvhF1viNHEKUe/W7CLl7yIlr5WriqnR6Mvagopie7RXmmVUnlNrWjExOjlxvOdjMpkr5B4t+hhpQ3l/wmc/D5DXdoICKrWruztu5pgOXHd1WxYLSYB9cEdvmpKr0WWM/cTC5BN39YDnIVRuQwm5HIXP/K/D8GlxtZjNOXNUvdlkYQH9bkeWDFpVnmKZRVq54cwhWVhrJxNs/EgccVE3ZT+lgba7wduX2fNUv0vuB++CMLEyiqqFCDbtHb6H6nXrh8wUTM83ltdujkV9UY7EnuIqMMdVqGg5hVCkskcws+hZyWWaIq+zQ81nfRqOkxQFvzPo+jmctIEvQEZfz/D6D0SmkMkPOdyIk/C8in0OHCrI1ffCEXPHggUIpTlz0nVI8tbpFLLMouOchkiiLcD9J88=
  distributions: "sdist bdist_wheel"