deploy:
  provider: pypi
  user: mkb79
  password:
    secure: RrLPFfY6Ut7dVTq3Sub3XUbYFxlEhUSV8zacVSf3YBKl34HPdAFDzvDovo5sA5nbwVrInSZUpX1Fltfcp+qKB55J/WqfSre+L3L17r3dHQubBMEYkyL83AnjfrM9N/zPU2PxZGrJz73JQdhtWYWyW0TDVjUIkkMZEcrl2Els2hGqy2c7Yhl/GbUlk70z2wPZIh2Bhp9PikP7N96YLiaSy51QwisMIYPtOuLJ6ybcy87G/HncS3syMO/McWfVLNRML31QTYltmxXc0pj9GuzoPamtorK+cCLLLLZ13h1RcXFj9P3SDDTqnOdvX8F20mqX0o6C5pEMUKZClMSBsrnfmyV1sRg/FzLn1mUd5BoKfhaSupC73usNuJM60PHRS0uBjWLKaNdoGOiy8odNV4oxoErS1L5OWvteobarbi9dWmF1vJQ93xHtOg3EgSV28B9s5s3t0NDS6SrfeeRAyPpxkPiugsgaZ9kYCR+QE4TkoG6e6tv9vNvTzMUAlL6q9fDKqmevgee8CWIWxsxvmULH+1libz6KwWbRJAaywJGqYkgqAva0Uj0rqOwOsekj1GmD8wN5AdZpeJAarhZQ0lPmOMRGYdns6Ow+x3jY6D8Fdl6jMawQCfA4VOtexv1RWw9n+6wNBA70tpbaj8Owgvoqfmx7uLEM60ilFtVsm1aVYmE=
  distributions: sdist bdist_wheel
