sudo: false
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: pypi
  user: mkb79
  password:
    secure: Gg0QfyBVYyqBH+BtocTY4nDn+FzNV/QW/p1l0UKzOUqmE7dxzh6trDXyRYlqobmY0ppqf/uMC+Rd3Ra04aHToJpUZc6ifeoCBMYSQXjJv89DifIGEZuSCZBiYoMA4kI3iLEM0hs5aUawecvnwMqyQ23UrJjhRmDd4D7X2H8Dm1j+4aILsL1TiI9Rvo/ZUBkcgR+0Ae/+N3QHOhcXR3ySnofaLf4I0TjGRUi3XSVhSGhYwswnSfXL/zexgxz9JX0pLgEqt9+KeS74ZcWQR6tHrK6AK24jx2PXOKH5iq9ba9tB9etZF361i9JnFm+0MiYZ8toyxfo8dxwlMcdpYdvd3YVVgxs1tJK/smMt6ZlT+F9hFNHmmuW/fW6wXHTSH9KtxeQvlT0udBmo5JPXJfHj6v0fTUlCEjPgSRTtt3sCrr+XKRobXpZkPzAjjMbFVyGZvfn4vSX2Q8yI3P+2EelBjLQtLI/0GbS9pfUWsXH6JeTAiA4oqCyxxEXm69M71CamUN/Z77PI8xev+wh5yOSpZxSjJ9AiB4rfS0q/yhZo+BzPFrAOEhoOFq0KaKUe4QbFeYVetVBn1rGGDUYImL/lFYLQ1P8Q2yLZL7GBIIx0bz381Q3JVL6j08CdnTSG379rx7t4d5M4fJDTt9+PgEbaOEHzdIF7Q+YA0YJcGS+XXMc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: mkb79/Audible
